In [1]:
import urllib2
response = urllib2.urlopen('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data')
data_file = response.read()

In [3]:
with open("adult.data", "wb") as code:
    code.write(data_file)

In [8]:
import os
import sys
from six.moves.urllib.request import urlretrieve

url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
last_percent_reported = None
# data_root = '.' # Change me to store data elsewhere
data_root = '/Users/jiqiyang/Documents/CS/AI/Week1'
def download_progress_hook(count, blockSize, totalSize):
  """A hook to report the progress of a download. This is mostly intended for users with
  slow internet connections. Reports every 5% change in download progress.
  """
  global last_percent_reported
  percent = int(count * blockSize * 100 / totalSize)

  if last_percent_reported != percent:
    if percent % 5 == 0:
      sys.stdout.write("%s%%" % percent)
      sys.stdout.flush()
    else:
      sys.stdout.write(".")
      sys.stdout.flush()
      
    last_percent_reported = percent
        
def maybe_download(filename, expected_bytes, force=False):
  """Download a file if not present, and make sure it's the right size."""
  dest_filename = os.path.join(data_root, filename)
  if force or not os.path.exists(dest_filename):
    print('Attempting to download:', filename) 
    filename, _ = urlretrieve(url + filename, dest_filename, reporthook=download_progress_hook)
    print('\nDownload Complete!')
  statinfo = os.stat(dest_filename)
  if statinfo.st_size == expected_bytes:
    print('Found and verified', dest_filename)
  else:
    raise Exception(
      'Failed to verify ' + dest_filename + '. Can you get to it with a browser?')
  return dest_filename

train_filename = maybe_download('data.data', 3974305)

('Attempting to download:', 'data.data')
0%.
Download Complete!


Exception: Failed to verify /Users/jiqiyang/Documents/CS/AI/Week1/data.data. Can you get to it with a browser?

In [1]:
import os

files = os.listdir(".")      
for filename in files:
    portion = os.path.splitext(filename)
    if portion[1] == ".data":   
        newname = portion[0] + ".csv"   
        os.rename(filename,newname)

In [2]:
from sklearn.preprocessing import StandardScaler
from pandas import read_csv
from numpy import set_printoptions

print('\nStandardize using sklearn')
filename = 'adult.csv'
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']
data_frame = read_csv(filename, names=names)
array = data_frame.values

# Separate array into input and output components
X = array[:, 0:14]
Y = array[:, 14]
scaler = StandardScaler().fit(X)
standardizedX = scaler.transform(X)

# Summarize transformed data
set_printoptions(precision=3)
print(standardizedX[0:5, :])


# -- Standardize from scratch -- #
print('\nStandardize from scratch')
# -- Standardize from scratch -- #
# Calculate data mean and standard deviation
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)

# The values for each attribute now have a mean of 0 and standard deviation of 1
X_scaled = (X - X_mean) / X_std

print(X_scaled[0:5, :])


Standardize using sklearn


ValueError: could not convert string to float: United-States

In [3]:
?read_csv

In [48]:
data_set = read_csv('./adult.csv', header=None, na_values=['?'], skipinitialspace=True, keep_default_na=True)

#Drop the lines which has NaN values
data_set.dropna(inplace=True)
print(data_set.shape)

(30162, 15)


In [49]:
# Drop the duplicated line
data_set.drop_duplicates(inplace=True)
print(data_set.shape)

# The summary of this data
print(data_set.describe())

(30139, 15)
                 0             2             4             10            11  \
count  30139.000000  3.013900e+04  30139.000000  30139.000000  30139.000000   
mean      38.441720  1.897950e+05     10.122532   1092.841202     88.439928   
std       13.131426  1.056586e+05      2.548738   7409.110596    404.445239   
min       17.000000  1.376900e+04      1.000000      0.000000      0.000000   
25%       28.000000  1.176275e+05      9.000000      0.000000      0.000000   
50%       37.000000  1.784170e+05     10.000000      0.000000      0.000000   
75%       47.000000  2.376045e+05     13.000000      0.000000      0.000000   
max       90.000000  1.484705e+06     16.000000  99999.000000   4356.000000   

                 12  
count  30139.000000  
mean      40.934703  
std       11.978753  
min        1.000000  
25%       40.000000  
50%       40.000000  
75%       45.000000  
max       99.000000  


In [51]:
print(data_set.head(n=10))

   0                 1       2          3   4                      5   \
0  39         State-gov   77516  Bachelors  13          Never-married   
1  50  Self-emp-not-inc   83311  Bachelors  13     Married-civ-spouse   
2  38           Private  215646    HS-grad   9               Divorced   
3  53           Private  234721       11th   7     Married-civ-spouse   
4  28           Private  338409  Bachelors  13     Married-civ-spouse   
5  37           Private  284582    Masters  14     Married-civ-spouse   
6  49           Private  160187        9th   5  Married-spouse-absent   
7  52  Self-emp-not-inc  209642    HS-grad   9     Married-civ-spouse   
8  31           Private   45781    Masters  14          Never-married   
9  42           Private  159449  Bachelors  13     Married-civ-spouse   

                  6              7      8       9      10  11  12  \
0       Adm-clerical  Not-in-family  White    Male   2174   0  40   
1    Exec-managerial        Husband  White    Male      0 

In [52]:
from sklearn.preprocessing import LabelEncoder

# Lable Encoding the feature values which is 'object' type
le = LabelEncoder()
for col in data_set.columns.values:
    print(data_set[col].dtypes)
    if data_set[col].dtypes == 'object':
        le.fit(data_set[col].values)
        data_set[col] = le.transform(data_set[col])
        
print(data_set.head(n=30))

int64
object
int64
object
int64
object
object
object
object
object
int64
int64
int64
object
object
    0   1       2   3   4   5   6   7   8   9      10    11  12  13  14
0   39   5   77516   9  13   4   0   1   4   1   2174     0  40  38   0
1   50   4   83311   9  13   2   3   0   4   1      0     0  13  38   0
2   38   2  215646  11   9   0   5   1   4   1      0     0  40  38   0
3   53   2  234721   1   7   2   5   0   2   1      0     0  40  38   0
4   28   2  338409   9  13   2   9   5   2   0      0     0  40   4   0
5   37   2  284582  12  14   2   3   5   4   0      0     0  40  38   0
6   49   2  160187   6   5   3   7   1   2   0      0     0  16  22   0
7   52   4  209642  11   9   2   3   0   4   1      0     0  45  38   1
8   31   2   45781  12  14   4   9   1   4   0  14084     0  50  38   1
9   42   2  159449   9  13   2   3   0   4   1   5178     0  40  38   1
10  37   2  280464  15  10   2   3   0   2   1      0     0  80  38   1
11  30   5  141297   9  13   2   9   

In [53]:
# Convert the pandas dataframe to nparray
data_set = data_set.as_matrix().astype(float)

In [54]:
# Split the data to Training data and Testing Data : 80% Training()  and 20% Testing ()
x_train = data_set[0:24111, :-2]
y_train = data_set[0:24111, -1]

x_test = data_set[-6028:, :-2]
y_test = data_set[-6028:, -1]

print("x_train:" + str(x_train.shape))
print("y_train:" + str(y_train.shape))
print("x_test:" + str(x_test.shape))
print("y_test:" + str(y_test.shape))

x_train:(24111, 13)
y_train:(24111,)
x_test:(6028, 13)
y_test:(6028,)


In [55]:
from sklearn.preprocessing import Normalizer

# Normalize the training and testing data
norm = Normalizer(norm='l2').fit(x_train)
x_train = norm.transform(x_train)
x_test = norm.transform(x_test)
print("Normalized x_train:\n" + str(x_train[:1, :]))
print("Normalized x_test:\n" + str(x_test[:1, :]))

Normalized x_train:
[[  5.02924039e-04   6.44774410e-05   9.99606663e-01   1.16059394e-04
    1.67641346e-04   5.15819528e-05   0.00000000e+00   1.28954882e-05
    5.15819528e-05   1.28954882e-05   2.80347913e-02   0.00000000e+00
    5.15819528e-04]]
Normalized x_test:
[[  2.12685731e-04   9.66753324e-06   9.99999971e-01   5.31714328e-05
    4.35038996e-05   1.93350665e-05   5.31714328e-05   9.66753324e-06
    1.93350665e-05   0.00000000e+00   0.00000000e+00   0.00000000e+00
    7.25064993e-05]]


In [56]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
# KNN clustering
knn=KNeighborsClassifier(n_neighbors=2)
knn.fit(x_train, y_train)
accuracy_score(y_test, knn.predict(x_test))

0.78682813536828133

In [62]:
# rescale data
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Separate array into input and output components
X = data_set[:, 0:14]
Y = data_set[:, 14]
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)

# Summarize transformed data
set_printoptions(precision=3)
print(rescaledX[0:5, :])


# -- Rescale from scratch -- #
print('\nRescale from scratch')
# -- Rescale from scratch -- #
# Define scale range min and max
MIN = 0
MAX = 1

# Calculate X min and max for each attribute
# axis=0 calculates along each column
X_min = np.min(X, axis=0)
X_max = np.max(X, axis=0)

# Calculate X_std and X_scaled
X_std = (X - X_min) / (X_max - X_min)
X_scaled = X_std * (MAX - MIN) + MIN

print(X_scaled[0:5, :])
print('\n Simpler Way')

# -- Simpler way to do it -- #
X_std_2 = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled_2 = X_std_2 * (MAX - MIN) + MIN

print(X_scaled_2[0:5, :])

[[ 0.301  0.833  0.043  0.6    0.8    0.667  0.     0.2    1.     1.     0.022
   0.     0.398  0.95 ]
 [ 0.452  0.667  0.047  0.6    0.8    0.333  0.231  0.     1.     1.     0.
   0.     0.122  0.95 ]
 [ 0.288  0.333  0.137  0.733  0.533  0.     0.385  0.2    1.     1.     0.
   0.     0.398  0.95 ]
 [ 0.493  0.333  0.15   0.067  0.4    0.333  0.385  0.     0.5    1.     0.
   0.     0.398  0.95 ]
 [ 0.151  0.333  0.221  0.6    0.8    0.333  0.692  1.     0.5    0.     0.
   0.     0.398  0.1  ]]

Rescale from scratch
[[ 0.301  0.833  0.043  0.6    0.8    0.667  0.     0.2    1.     1.     0.022
   0.     0.398  0.95 ]
 [ 0.452  0.667  0.047  0.6    0.8    0.333  0.231  0.     1.     1.     0.
   0.     0.122  0.95 ]
 [ 0.288  0.333  0.137  0.733  0.533  0.     0.385  0.2    1.     1.     0.
   0.     0.398  0.95 ]
 [ 0.493  0.333  0.15   0.067  0.4    0.333  0.385  0.     0.5    1.     0.
   0.     0.398  0.95 ]
 [ 0.151  0.333  0.221  0.6    0.8    0.333  0.692  1.     0.5    0.   

In [63]:
# standardize data
from sklearn.preprocessing import StandardScaler
from numpy import set_printoptions

scaler = StandardScaler().fit(X)
standardizedX = scaler.transform(X)

# Summarize transformed data
set_printoptions(precision=3)
print(standardizedX[0:5, :])


# -- Standardize from scratch -- #
print('\nStandardize from scratch')
# -- Standardize from scratch -- #
# Calculate data mean and standard deviation
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)

# The values for each attribute now have a mean of 0 and standard deviation of 1
X_scaled = (X - X_mean) / X_std

print(X_scaled[0:5, :])

[[ 0.043  2.935 -1.063 -0.35   1.129  0.948 -1.479 -0.261  0.385  0.693
   0.146 -0.219 -0.078  0.265]
 [ 0.88   1.887 -1.008 -0.35   1.129 -0.387 -0.735 -0.886  0.385  0.693
  -0.148 -0.219 -2.332  0.265]
 [-0.034 -0.209  0.245  0.175 -0.44  -1.722 -0.238 -0.261  0.385  0.693
  -0.148 -0.219 -0.078  0.265]
 [ 1.109 -0.209  0.425 -2.448 -1.225 -0.387 -0.238 -0.886 -2.011  0.693
  -0.148 -0.219 -0.078  0.265]
 [-0.795 -0.209  1.407 -0.35   1.129 -0.387  0.754  2.236 -2.011 -1.444
  -0.148 -0.219 -0.078 -5.307]]

Standardize from scratch
[[ 0.043  2.935 -1.063 -0.35   1.129  0.948 -1.479 -0.261  0.385  0.693
   0.146 -0.219 -0.078  0.265]
 [ 0.88   1.887 -1.008 -0.35   1.129 -0.387 -0.735 -0.886  0.385  0.693
  -0.148 -0.219 -2.332  0.265]
 [-0.034 -0.209  0.245  0.175 -0.44  -1.722 -0.238 -0.261  0.385  0.693
  -0.148 -0.219 -0.078  0.265]
 [ 1.109 -0.209  0.425 -2.448 -1.225 -0.387 -0.238 -0.886 -2.011  0.693
  -0.148 -0.219 -0.078  0.265]
 [-0.795 -0.209  1.407 -0.35   1.129 -0.387  0

In [64]:
# normalize_data
from sklearn.preprocessing import Normalizer

# L1 norm
scaler = Normalizer(norm='l1').fit(X)
normalizedX = scaler.transform(X)

# Summarize transformed data
set_printoptions(precision=3)
print(normalizedX[0:5, :])


# -- Normalize from scratch--L1 norm -- #
# L1 norm
print('\nNormalize from scratch--L1 norm')
norms = np.abs(X).sum(axis=1)

X_normalized = X / norms[:, np.newaxis]

print(X_normalized[0:5, :])

# -- Normalize using sklearn--L2 norm -- #
# L2 norm
print('\nNormalize using sklearn--L2 norm')
scaler = Normalizer(norm='l2').fit(X)
normalizedX = scaler.transform(X)

# Summarize transformed data
set_printoptions(precision=3)
print(normalizedX[0:5, :])

# -- Normalize from scratch--L2 norm -- #
# L2 norm
print('\nNormalize from scratch--L2 norm')
norms = np.einsum('ij,ij->i', X, X)
np.sqrt(norms, norms)
X_normalized = X / norms[:, np.newaxis]
print(X_normalized[0:5, :])

[[  4.885e-04   6.262e-05   9.708e-01   1.127e-04   1.628e-04   5.010e-05
    0.000e+00   1.252e-05   5.010e-05   1.252e-05   2.723e-02   0.000e+00
    5.010e-04   4.759e-04]
 [  5.992e-04   4.793e-05   9.984e-01   1.079e-04   1.558e-04   2.397e-05
    3.595e-05   0.000e+00   4.793e-05   1.198e-05   0.000e+00   0.000e+00
    1.558e-04   4.554e-04]
 [  1.761e-04   9.268e-06   9.993e-01   5.097e-05   4.171e-05   0.000e+00
    2.317e-05   4.634e-06   1.854e-05   4.634e-06   0.000e+00   0.000e+00
    1.854e-04   1.761e-04]
 [  2.257e-04   8.515e-06   9.994e-01   4.258e-06   2.980e-05   8.515e-06
    2.129e-05   0.000e+00   8.515e-06   4.258e-06   0.000e+00   0.000e+00
    1.703e-04   1.618e-04]
 [  8.271e-05   5.908e-06   9.997e-01   2.659e-05   3.840e-05   5.908e-06
    2.659e-05   1.477e-05   5.908e-06   0.000e+00   0.000e+00   0.000e+00
    1.182e-04   1.182e-05]]

Normalize from scratch--L1 norm
[[  4.885e-04   6.262e-05   9.708e-01   1.127e-04   1.628e-04   5.010e-05
    0.000e+00   1

In [65]:
# binarize data
from sklearn.preprocessing import Binarizer

binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)

# Summarize transformed data
set_printoptions(precision=3)
print(binaryX[0:5, :])

# -- Binarize from scratch -- #
print('\nBinarize from scratch')
threshold = 0.0
cond = X > threshold
not_cond = np.logical_not(cond)
X_binarized = X
X_binarized[cond] = 1
X_binarized[not_cond] = 0

print(X_binarized[0:5, :])

[[ 1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  0.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  0.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  0.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.]]

Binarize from scratch
[[ 1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  0.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  0.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  0.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.]]
